### ISSUE TITLE
what is method for solving level 2?

### ISSUE THREAD

**Issue by dvikan** [etse/HackMe#1]
what is method for solving level 2? the one where password is slashdot

**Comment by dvikan** [comment]
ditto for level 4

**Comment by etse** [comment]
Level 2: Very specific for the target audience. Its the avatar of one of the most knows users on the forum I ran the competition on.

Level 4: The picture has metadata

**Comment by dvikan** [comment]
okay. i tried exif and strings and vlc. did not find

**Comment by etse** [comment]
Try [http://exifdata.com/](exifdata) to use to upload the image, it should show the password un the detailed view
